version: '3'

services:
    webserver:
        image: 'nginx:latest'
        restart: 'always'
        volumes:
          - 'data:/usr/share/nginx/html'
          - './:/usr/share/nginx/html'
        ports:
          - '80:80'
        environment:
          - NGINX_PORT=80

volumes:
    data:
        external: true